

export const REMOVE_TODOLIST='REMOVE-TODOLIST' as const

export const ADD_TODOLIST='ADD-TODOLIST' as const

export const CHANGE_TODOLIST_TITLE='CHANGE-TODOLIST-TITLE' as const

export const CHANGE_TODOLIST_FILTER='CHANGE-TODOLIST-FILTER' as const